<a href="https://colab.research.google.com/github/mohamedjunaidm2025cse-create/FDS-Lab-Exp/blob/main/exp6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
data = {
    'Country': ['India', 'USA', 'Japan', 'USA', 'Japan',
                'India', 'USA', 'India', 'Japan', 'India'],
    'Age': [25, 32, 28, 45, np.nan, 36, 29, 41, 50, 33],
    'Salary': [35000, 65000, 48000, 90000, 72000,
               55000, np.nan, 82000, 95000, 60000],
    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes',
                  'No', 'Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

features = df.iloc[:, :-1].values
label = df.iloc[:, -1].values

from sklearn.impute import SimpleImputer

age = SimpleImputer(strategy='mean')
salary = SimpleImputer(strategy='mean')

features[:, [1]] = age.fit_transform(features[:, [1]])
features[:, [2]] = salary.fit_transform(features[:, [2]])

from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)
Country = oh.fit_transform(features[:, [0]])

print("\nEncoded Country:")
print(Country)

final_set = np.concatenate(
    (Country, features[:, [1, 2]]),
    axis=1
)

print("\nFinal Set:")
print(final_set)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
feat_standard_scaler = sc.fit_transform(final_set)

print("\nStandard Scaled Data:")
print(feat_standard_scaler)

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler(feature_range=(0, 1))
feat_minmax_scaler = mms.fit_transform(final_set)

print("\nMin-Max Scaled Data:")
print(feat_minmax_scaler)

Original Dataset:
  Country   Age   Salary Purchased
0   India  25.0  35000.0       Yes
1     USA  32.0  65000.0        No
2   Japan  28.0  48000.0       Yes
3     USA  45.0  90000.0        No
4   Japan   NaN  72000.0       Yes
5   India  36.0  55000.0        No
6     USA  29.0      NaN       Yes
7   India  41.0  82000.0        No
8   Japan  50.0  95000.0       Yes
9   India  33.0  60000.0        No

Encoded Country:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

Final Set:
[[1.0 0.0 0.0 25.0 35000.0]
 [0.0 0.0 1.0 32.0 65000.0]
 [0.0 1.0 0.0 28.0 48000.0]
 [0.0 0.0 1.0 45.0 90000.0]
 [0.0 1.0 0.0 35.44444444444444 72000.0]
 [1.0 0.0 0.0 36.0 55000.0]
 [0.0 0.0 1.0 29.0 66888.88888888889]
 [1.0 0.0 0.0 41.0 82000.0]
 [0.0 1.0 0.0 50.0 95000.0]
 [1.0 0.0 0.0 33.0 60000.0]]

Standard Scaled Data:
[[ 1.22474487 -0.65465367 -0.65465367 -1.39791828 -1.79819479]
 [-0.81649658 -0.65465367  1.52752523 -0.4610156  -0.106