<a href="https://colab.research.google.com/github/mohamedjunaidm2025cse-create/FDS-Lab-Exp/blob/main/exp_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

# Create a random array of 9 elements
arr = np.random.randint(1, 100, size=9)
print("Original Array:")
print(arr)

# Find square roots
print("\nSquare Root:")
print(np.sqrt(arr))

# Find array dimension
print("\nArray Dimension:")
print(arr.ndim)

# Convert into a 3x3 matrix
matrix = arr.reshape(3, 3)
print("\n3x3 Matrix:")
print(matrix)

# Check matrix dimension
print("\nMatrix Dimension:")
print(matrix.ndim)

# Flatten the matrix
flat_arr = matrix.flatten()
print("\nFlattened Array:")
print(flat_arr)

# Reshape the matrix
reshaped = matrix.reshape(3, 3)
print("\nReshaped Matrix:")
print(reshaped)

# Access selected elements
print("\nLast Row, Second and Third Elements:")
print(reshaped[2, 1:3])

print("\nSecond Row, Second and Third Elements:")
print(reshaped[1:2, 1:3])

# Select an empty slice
print("\nEmpty Slice:")
print(matrix[:, 0:0])

# Select the first column of the first two rows
print("\nFirst Column of First Two Rows:")
print(matrix[0:2, 0:1])

# Select the first column of all rows
print("\nFirst Column:")
print(matrix[:, 0:1])

# Select the last two rows
print("\nLast Two Rows:")
print(matrix[1:3])

Original Array:
[49 41 49 99 47 97  3 60 85]

Square Root:
[7.         6.40312424 7.         9.94987437 6.8556546  9.8488578
 1.73205081 7.74596669 9.21954446]

Array Dimension:
1

3x3 Matrix:
[[49 41 49]
 [99 47 97]
 [ 3 60 85]]

Matrix Dimension:
2

Flattened Array:
[49 41 49 99 47 97  3 60 85]

Reshaped Matrix:
[[49 41 49]
 [99 47 97]
 [ 3 60 85]]

Last Row, Second and Third Elements:
[60 85]

Second Row, Second and Third Elements:
[[47 97]]

Empty Slice:
[]

First Column of First Two Rows:
[[49]
 [99]]

First Column:
[[49]
 [99]
 [ 3]]

Last Two Rows:
[[99 47 97]
 [ 3 60 85]]
